# Generated by Django 2.1.5 on 2019-01-30 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brumadinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedlocation',
            name='data_visita',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data desta visita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitedlocation',
            name='radius',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Raio aproximado ao redor do ponto'),
        ),
    ]
