# Generated by Django 2.1.3 on 2019-02-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brumadinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geolocation',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
