# Generated by Django 2.1.5 on 2019-01-30 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brumadinho', '0002_auto_20190130_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedlocation',
            name='data_visita',
        ),
        migrations.AddField(
            model_name='visitedlocation',
            name='date_visited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Visit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitedlocation',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Visit Notes'),
        ),
        migrations.AlterField(
            model_name='visitedlocation',
            name='radius',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Approx. radius visited from marker'),
        ),
    ]
